Repository pboivin/intuit-auto-test, pull requests merged in 2021-08, with the labels that each got.

#1 fix: Add copyright notice to README.md
  README.md
Labels: patch, release

#5 Update bar documentation
  docs/bar.md
Labels: patch, release

#6 feat(foo): Add more foo
  src/foo.js
Labels: minor, release

#9 Update foo.js
  src/foo.js
Labels: enhancement

#10 Update bar.js
  src/bar.js
Labels: enhancement

#11 Update foo.md
  docs/foo.md
Labels: bug, minor, release

#12 Major refactor of foo and bar
  src/bar.js
  src/foo.js
Labels: major, release

#15 Update foo.js
  src/foo.js
Labels: enhancement

#16 fix(docs): Bla bla
  docs/foo.md
Labels: minor, release

#17 Update foo.js
  src/foo.js
Labels: minor

#18 Update bar.js
  src/bar.js
Labels: patch, release

#19 Feat/version bump
  .auto/bump-package-version.js
  .autorc
  package.json
  src/TwillServiceProvider.php
Labels: minor, release

#20 feat: Version bump
  .auto/bump-package-version.js
  .autorc
Labels: minor, release

#21 Update foo.js
  src/foo.js
Labels: minor, release

#22 Update foo.js
  src/foo.js
Labels: minor, release

#24 Update foo.js
  src/foo.js
Labels: minor, release

#25 Update foo.js
  src/foo.js
Labels: minor, release

#26 Update foo.js
  src/foo.js
Labels: minor, release

#28 Update bar.js
  src/bar.js
Labels: major

#27 Update foo.js
  src/foo.js
Labels: patch, release

#29 Update bar.js
  src/bar.js
Labels: minor, release

#30 Update foo.js
  src/foo.js
Labels: minor, release

#31 Update foo.js
  src/foo.js
Labels: minor

#32 Update bar.js
  src/bar.js
Labels: major, release

#33 Update foo.js
  src/foo.js
Labels: patch, release

#34 Update foo.js
  src/foo.js
Labels: major, release

#35 fix: Update bar.js
  src/bar.js
Labels: patch, release

#36 Update foo.js
  src/foo.js
Labels: patch, release
